import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight:["400","700"],preload:true ,adjustFontFallback: true,style:"normal",fallback: ['system-ui', 'arial']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='scroll-smooth'  lang="en">
      <body  className={poppins.className}>{children}</body>
    </html>
  )
}
